#!/usr/bin/env bash
# host/setup.sh — Universal host system setup for Debian 13
# Auto-detects GPU (Intel/AMD/NVIDIA), configures WiFi, ZRAM, DNS, and more.
# Works on any hardware — give this to your friends.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../scripts/helpers.sh
source "$SCRIPT_DIR/../scripts/helpers.sh"

HYPR_GPU_CONF="$HOME/.config/hypr/gpu-env.conf"

# ══════════════════════════════════════════════════════════════════════════════
#  1. REPOS & UPDATES
# ══════════════════════════════════════════════════════════════════════════════

info "Ensuring non-free and non-free-firmware repos are enabled..."
if ! grep -q "non-free-firmware" /etc/apt/sources.list 2>/dev/null && \
   ! grep -rq "non-free-firmware" /etc/apt/sources.list.d/ 2>/dev/null; then
    sudo sed -i 's/main$/main contrib non-free non-free-firmware/' /etc/apt/sources.list 2>/dev/null || true
    if ls /etc/apt/sources.list.d/*.sources &>/dev/null; then
        sudo sed -i 's/Components: main$/Components: main contrib non-free non-free-firmware/' \
            /etc/apt/sources.list.d/*.sources
    fi
    success "Non-free repos enabled"
else
    success "Non-free repos already enabled"
fi

info "Updating package database..."
sudo apt-get update
info "Upgrading existing packages..."
sudo apt-get upgrade -y

# ══════════════════════════════════════════════════════════════════════════════
#  2. BASE PACKAGES (GPU-agnostic)
# ══════════════════════════════════════════════════════════════════════════════

info "Installing base host packages..."
readarray -t PACKAGES < <(grep -v '^\s*#' "$SCRIPT_DIR/packages.txt" | grep -v '^\s*$')
apt_install "${PACKAGES[@]}"
success "Base packages installed"

# ══════════════════════════════════════════════════════════════════════════════
#  3. GPU AUTO-DETECTION & DRIVER INSTALL
# ══════════════════════════════════════════════════════════════════════════════

detect_gpu() {
    # Returns: nvidia, amd, intel, or unknown
    local gpu_info
    gpu_info=$(lspci -nn 2>/dev/null | grep -iE "VGA|3D|Display" || true)

    if echo "$gpu_info" | grep -qi "NVIDIA"; then
        echo "nvidia"
    elif echo "$gpu_info" | grep -qi "AMD\|ATI\|Radeon"; then
        echo "amd"
    elif echo "$gpu_info" | grep -qi "Intel"; then
        echo "intel"
    else
        echo "unknown"
    fi
}

GPU_VENDOR=$(detect_gpu)
info "Detected GPU: $GPU_VENDOR"

case "$GPU_VENDOR" in
    nvidia)
        info "Installing NVIDIA drivers..."
        apt_install nvidia-driver nvidia-kernel-dkms

        # NVIDIA DRM modesetting (required for Wayland)
        NVIDIA_MODESET_CONF="/etc/modprobe.d/nvidia-options.conf"
        if [[ ! -f "$NVIDIA_MODESET_CONF" ]]; then
            echo 'options nvidia_drm modeset=1 fbdev=1' | sudo tee "$NVIDIA_MODESET_CONF" > /dev/null
            success "NVIDIA DRM modesetting enabled"
        fi

        # NVIDIA initramfs modules
        NVIDIA_MODULES="/etc/initramfs-tools/modules"
        for mod in nvidia nvidia_modeset nvidia_uvm nvidia_drm; do
            if ! grep -q "^${mod}$" "$NVIDIA_MODULES" 2>/dev/null; then
                echo "$mod" | sudo tee -a "$NVIDIA_MODULES" > /dev/null
            fi
        done
        sudo update-initramfs -u
        success "NVIDIA initramfs updated"

        # Generate Hyprland GPU env
        mkdir -p "$(dirname "$HYPR_GPU_CONF")"
        cat > "$HYPR_GPU_CONF" <<'GPUEOF'
# Auto-generated by host/setup.sh — NVIDIA GPU detected
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = WLR_NO_HARDWARE_CURSORS,1
GPUEOF
        success "NVIDIA Hyprland env generated"
        ;;

    amd)
        info "Installing AMD GPU drivers..."
        apt_install mesa-vulkan-drivers mesa-va-drivers libva-glx2 \
            libvulkan1 vulkan-tools

        # Generate Hyprland GPU env
        mkdir -p "$(dirname "$HYPR_GPU_CONF")"
        cat > "$HYPR_GPU_CONF" <<'GPUEOF'
# Auto-generated by host/setup.sh — AMD GPU detected
env = LIBVA_DRIVER_NAME,radeonsi
env = AMD_VULKAN_ICD,RADV
env = ELECTRON_OZONE_PLATFORM_HINT,auto
GPUEOF
        success "AMD drivers + Hyprland env configured"
        ;;

    intel)
        info "Installing Intel GPU drivers..."
        apt_install mesa-vulkan-drivers intel-media-va-driver \
            libvulkan1 vulkan-tools

        # Generate Hyprland GPU env
        mkdir -p "$(dirname "$HYPR_GPU_CONF")"
        cat > "$HYPR_GPU_CONF" <<'GPUEOF'
# Auto-generated by host/setup.sh — Intel GPU detected
env = LIBVA_DRIVER_NAME,iHD
env = ELECTRON_OZONE_PLATFORM_HINT,auto
GPUEOF
        success "Intel drivers + Hyprland env configured"
        ;;

    *)
        warn "Unknown GPU vendor. Installing generic Mesa drivers..."
        apt_install mesa-vulkan-drivers libvulkan1

        mkdir -p "$(dirname "$HYPR_GPU_CONF")"
        cat > "$HYPR_GPU_CONF" <<'GPUEOF'
# Auto-generated by host/setup.sh — Generic GPU config
env = ELECTRON_OZONE_PLATFORM_HINT,auto
GPUEOF
        ;;
esac

# ══════════════════════════════════════════════════════════════════════════════
#  4. AUTOLOGIN ON TTY1
# ══════════════════════════════════════════════════════════════════════════════

info "Setting up autologin on TTY1..."
AUTOLOGIN_DIR="/etc/systemd/system/getty@tty1.service.d"
sudo mkdir -p "$AUTOLOGIN_DIR"
cat <<EOF | sudo tee "$AUTOLOGIN_DIR/autologin.conf" > /dev/null
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin $(whoami) --noclear %I \$TERM
Type=idle
EOF
sudo systemctl daemon-reload
success "Autologin configured for $(whoami) on TTY1"

# ══════════════════════════════════════════════════════════════════════════════
#  5. PIPEWIRE
# ══════════════════════════════════════════════════════════════════════════════

info "Enabling PipeWire..."
systemctl --user enable --now pipewire.socket pipewire-pulse.socket wireplumber.service 2>/dev/null || \
    info "PipeWire user services will start on next login"
success "PipeWire configured"

# ══════════════════════════════════════════════════════════════════════════════
#  6. MEDIATEK WIFI + NETWORK STABILITY
# ══════════════════════════════════════════════════════════════════════════════

info "Configuring WiFi for maximum stability..."

# Detect if MediaTek WiFi is present
WIFI_VENDOR=$(lspci -nn 2>/dev/null | grep -i "Network\|Wireless" || true)
if echo "$WIFI_VENDOR" | grep -qi "MediaTek\|MTK\|14c3"; then
    info "MediaTek WiFi detected — applying stability fixes..."

    # Disable power management (biggest cause of MediaTek WiFi drops)
    MEDIATEK_PM_CONF="/etc/modprobe.d/mediatek-wifi.conf"
    if [[ ! -f "$MEDIATEK_PM_CONF" ]]; then
        cat <<'MTEOF' | sudo tee "$MEDIATEK_PM_CONF" > /dev/null
# MediaTek WiFi stability — disable aggressive power saving
options mt76_connac_lib ps_disable=1
options mt7921e power_save=N
options mt7922e power_save=N
options mt7921_common power_save=0
MTEOF
        success "MediaTek power-save disabled"
    fi
fi

# NetworkManager WiFi stability settings (universal, benefits all chipsets)
NM_WIFI_CONF="/etc/NetworkManager/conf.d/99-wifi-stability.conf"
if [[ ! -f "$NM_WIFI_CONF" ]]; then
    sudo mkdir -p /etc/NetworkManager/conf.d
    cat <<'NMEOF' | sudo tee "$NM_WIFI_CONF" > /dev/null
[device]
# Use iwd backend for better MediaTek/modern WiFi support (if available)
# wifi.backend=iwd

# Disable MAC randomization for stable connections
wifi.scan-rand-mac-address=no

[connection]
# Disable WiFi power saving (prevents random disconnects)
wifi.powersave=2

# Faster DHCP — don't wait forever
ipv4.dhcp-timeout=30
ipv6.dhcp-timeout=30

# Stable DNS
connection.mdns=2
connection.llmnr=0
NMEOF
    success "NetworkManager WiFi stability configured"
fi

# Set regulatory domain (important for proper WiFi channel/power)
if command -v iw &>/dev/null; then
    # Best-effort: set to India, users can change
    sudo iw reg set IN 2>/dev/null || true
fi

# ══════════════════════════════════════════════════════════════════════════════
#  7. DNS-OVER-TLS (Quad9 + Cloudflare)
# ══════════════════════════════════════════════════════════════════════════════

info "Configuring DNS-over-TLS via systemd-resolved..."
sudo mkdir -p /etc/systemd/resolved.conf.d
cat <<'DNSEOF' | sudo tee /etc/systemd/resolved.conf.d/99-dns-tls.conf > /dev/null
[Resolve]
# Primary: Quad9 (malware blocking) + Cloudflare (speed)
DNS=9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net 1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com
FallbackDNS=9.9.9.9#dns.quad9.net 1.1.1.1#cloudflare-dns.com
DNSSEC=allow-downgrade
DNSOverTLS=opportunistic
MulticastDNS=yes
LLMNR=no
DNSEOF

# Point /etc/resolv.conf to systemd-resolved
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 2>/dev/null || true
sudo systemctl enable --now systemd-resolved 2>/dev/null || true
success "DNS-over-TLS configured (Quad9 + Cloudflare)"

# ══════════════════════════════════════════════════════════════════════════════
#  8. ZRAM (compressed swap in RAM)
# ══════════════════════════════════════════════════════════════════════════════

info "Configuring ZRAM..."

# Read total RAM
TOTAL_MEM_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
TOTAL_MEM_MB=$((TOTAL_MEM_KB / 1024))

if (( TOTAL_MEM_MB <= 8192 )); then
    ZRAM_SIZE="ram"
    info "RAM <= 8GB: ZRAM set to full RAM size"
else
    ZRAM_SIZE="ram - 2048"
    info "RAM > 8GB: ZRAM set to RAM - 2GB"
fi

sudo mkdir -p /etc/systemd
cat <<ZRAMEOF | sudo tee /etc/systemd/zram-generator.conf > /dev/null
[zram0]
zram-size = ${ZRAM_SIZE}
compression-algorithm = zstd
ZRAMEOF

# Swappiness tuning for ZRAM
cat <<'SYSEOF' | sudo tee /etc/sysctl.d/99-vm-zram.conf > /dev/null
# ZRAM-optimized VM parameters
vm.swappiness = 180
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0
vm.vfs_cache_pressure = 50
# Prevent "map allocation failed" in heavy apps/games
vm.max_map_count = 2147483642
SYSEOF

sudo sysctl --load /etc/sysctl.d/99-vm-zram.conf > /dev/null 2>&1 || true
success "ZRAM configured ($TOTAL_MEM_MB MB RAM detected)"

# ══════════════════════════════════════════════════════════════════════════════
#  9. SYSTEM SERVICES
# ══════════════════════════════════════════════════════════════════════════════

info "Enabling system services..."
SERVICES=(
    "NetworkManager.service"
    "systemd-timesyncd.service"
    "fstrim.timer"
)

for svc in "${SERVICES[@]}"; do
    if systemctl list-unit-files "$svc" &>/dev/null; then
        sudo systemctl enable --now "$svc" 2>/dev/null || true
    fi
done
success "System services enabled"

# ══════════════════════════════════════════════════════════════════════════════
#  10. DISTROBOX
# ══════════════════════════════════════════════════════════════════════════════

if ! command -v distrobox &>/dev/null; then
    info "Installing distrobox..."
    curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
    success "Distrobox installed"
else
    success "Distrobox already installed"
fi

if command -v podman &>/dev/null; then
    success "Podman available"
else
    warn "Podman not found — should have been installed via packages.txt"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  11. VIRTUALIZATION
# ══════════════════════════════════════════════════════════════════════════════

info "Configuring libvirt..."
sudo systemctl enable --now libvirtd.service 2>/dev/null || true
if ! groups "$(whoami)" | grep -q libvirt; then
    sudo usermod -aG libvirt "$(whoami)"
    success "Added $(whoami) to libvirt group (re-login to take effect)"
else
    success "Already in libvirt group"
fi

# ══════════════════════════════════════════════════════════════════════════════
#  12. LOGROTATE TUNING
# ══════════════════════════════════════════════════════════════════════════════

info "Optimizing logrotate..."
cat <<'LOGEOF' | sudo tee /etc/logrotate.d/dotfiles-tuning > /dev/null
/var/log/syslog
/var/log/kern.log
/var/log/auth.log
{
    rotate 4
    weekly
    compress
    delaycompress
    missingok
    notifempty
}
LOGEOF
success "Logrotate optimized"

# ══════════════════════════════════════════════════════════════════════════════
#  DONE
# ══════════════════════════════════════════════════════════════════════════════

echo ""
info "Summary of detected hardware:"
echo "  GPU:  $GPU_VENDOR"
echo "  WiFi: $(echo "$WIFI_VENDOR" | head -1 | sed 's/.*: //' || echo 'not detected')"
echo "  RAM:  ${TOTAL_MEM_MB} MB"
echo "  ZRAM: $ZRAM_SIZE (zstd)"
echo ""
success "Host system setup complete!"
